### ISSUE TITLE
Not working on newly installed nginx+php7-fpm.

### ISSUE THREAD

**Issue by thekksed** [p4v800m/google-drive-proxy-jwplayer#3]
Do I need to adjust any settings? or maybe using apache?

Errors log;

`[error] 12445#12445: *1128 FastCGI sent in stderr: "PHP message: PHP Notice:  Undefined variable: title in /var/www/html/drive.php on line 12
PHP message: PHP Notice:  Undefined variable: susci in /var/www/html/drive.php on line 44
PHP message: PHP Notice:  Undefined variable: driver in /var/www/html/drive.php on line 49
PHP message: PHP Warning:  explode() expects parameter 2 to be string, array given in /var/www/html/drive.php on line 4
PHP message: PHP Warning:  explode() expects parameter 2 to be string, array given in /var/www/html/drive.php on line 4
PHP message: PHP Notice:  Undefined index: ... in /var/www/html/drive.php on line 62" while reading response header from upstream, client: , server: _, request: "GET /drive.php?id=... HTTP/1.1", upstream: "fastcgi://unix:/run/php/php7.0-fpm.sock:", host: ""`

**Comment by p4v800m** [comment]
no idea, I already used in php7 easyengine and centminmod and I had no problems.
